### ISSUE TITLE
Fix Altinn2 prioritet selenium tests som feiler i selenium og pipeline

### ISSUE THREAD

**Issue by sneha-sirure** [Altinn/altinn-tests#86]
Det er 64 testene som feiler i selenium som mangler en fikse, men siden vi skal flytte til nye brukerflate i march da vi tenkte at vi skal fikse de som er prioritet for å fikse og ikke brekker noe i Altinn 2 pga nye endring. 

### Testene som feiler og prioritet for å fikse. 

```[tasklist]
### Tasks
- [x] DecodeJSONWebTokenAfterGivingConsentREST (feiler pga utgått sertifikat)
- [x] ConsentRequestWithRedirectURLHavingFragments (feiler pga utgått sertifikat)
- [x] VerifyTheConsentHasBeenDeletedREST (feiler pga utgått sertifikat)
- [x] VerifyThatConsentHasBeenLoggedAsUsedREST (feiler pga utgått sertifikat)
- [x] RejectConsentRequestedViaREST (feiler pga utgått sertifikat)
- [x] ApproveAConsentRequest (feiler pga utgått sertifikat)
- [x] ClientDelegationsForEnkeltpersonsforetakShouldGiveAccessToTheSameRolesForInnehaver (testbruker er sikkerhetsnivå 2, men må være 3)
- [x] CreateDelegationRequestToSsnOnBehalfOfReporteeViaRESTAndCheckTextInDelegationRequest
- [x] CreateDelegationRequestViaRESTAndVerifyRedirecturlAndRejectRequest
- [x] RequestAccessAndApproveAccessToServicesWithAccess
- [x] RequestAccessAndDeleteRequestAsAccessController
- [x] RejectAccessRequestWithNoAccessToRequestedService
- [x] VerifyTheSigningRightIsNotVisibleWhenTheReportingServiceIsWithoutSigning
- [x] RequestAccessModal_SearchAndExitProcess
```
